Repository Ref-Hub/RefHub_FE, pull requests merged in 2025-03, with the labels that each got.

#53 fix: 로그인 페이지 이메일 입력 필드 유효성 검사 개선 (QA #0003)
  src/pages/auth/LoginPage.tsx
Labels: bug

#54 fix: 중복 계정 가입 시 인증번호 전송 방지 및 오류 메시지 출력
  src/pages/auth/SignupPage.tsx
  src/services/auth.ts
Labels: bug

#55 fix: 검색 바 초기화 처리(QA #0082-0083, #0086, #0233)
  src/components/common/SearchBar.tsx
  src/components/layout/MainHeader.tsx
Labels: bug

#56 fix: 드롭메뉴 오류 및 레퍼런스 영역 초과 시 키워드 개수 노출 처리
  src/components/common/Dropdown.tsx
  src/components/reference/ReferenceCard.tsx
  src/components/reference/ReferenceList.tsx
Labels: bug

#57 fix: 사용자 권한에 따른 레퍼런스 더보기 및 체크박스 노출 여부 처리
  src/components/reference/ReferenceCard.tsx
  src/components/reference/ReferenceList.tsx
  src/pages/collection/CollectionDetailPage.tsx
  src/pages/reference/ReferenceDetailPage.tsx
  src/pages/reference/ReferenceListPage.tsx
  src/types/reference.ts
Labels: bug

#58 fix: 컬렉션 상세 삭제모드 오류 수정
  src/components/common/Alert.tsx
  src/components/common/FloatingButton.tsx
  src/components/reference/ReferenceCard.tsx
  src/pages/collection/CollectionDetailPage.tsx
Labels: bug

#60 merge: 로그인 오류 처리 개선 및 UI 개선 사항
  dev-dist/sw.js
  src/assets/images/instar_icon.svg
  src/assets/star-filled.svg
  src/assets/star-outline.svg
  src/components/common/Alert.tsx
  src/components/common/Dropdown.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/SearchBar.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MainHeader.tsx
  src/components/reference/ReferenceCard.tsx
  src/components/reference/ReferenceList.tsx
  src/contexts/ToastProvider.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/collection/CollectionDetailPage.tsx
  src/pages/reference/ReferenceDetailPage.tsx
  src/pages/reference/ReferenceListPage.tsx
  src/services/auth.ts
  src/types/reference.ts
  src/utils/errorHandler.ts
Labels: bug, enhancement

#62 fix: 이모지 등 유효하지 않은 문자 입력 방지
  src/components/common/Input.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/PasswordResetPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: bug

#63 Feature/dark mode support
  src/components/common/ThemeToggle.tsx
  src/components/layout/AuthHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainHeader.tsx
  src/components/layout/ThemeProvider.tsx
  src/hooks/useTheme.ts
  src/store/theme.ts
  tailwind.config.js
Labels: enhancement

#64 merge: dark mode phase 1
  src/components/common/Input.tsx
  src/components/common/ThemeToggle.tsx
  src/components/layout/AuthHeader.tsx
  src/components/layout/Header.tsx
  src/components/layout/MainHeader.tsx
  src/components/layout/ThemeProvider.tsx
  src/hooks/useTheme.ts
  src/pages/auth/LoginPage.tsx
  src/pages/auth/PasswordResetPage.tsx
  src/pages/auth/SignupPage.tsx
  src/store/theme.ts
  tailwind.config.js
Labels: enhancement

#66 fix: 컬렉션 수정 모달, 플로팅 버튼 수정
  src/components/collection/Modal.tsx
  src/components/common/FloatingButton.tsx
  src/pages/reference/ReferenceListPage.tsx
Labels: bug

#67 merge: main < develop
  dev-dist/sw.js
  src/components/collection/Modal.tsx
  src/components/common/FloatingButton.tsx
  src/components/layout/Footer.tsx
  src/pages/reference/ReferenceListPage.tsx
Labels: enhancement

#68 fix: 로그인 페이지 개선 - 레이아웃 최적화 및 이메일 유효성 검사 추가
  src/components/common/Input.tsx
  src/pages/auth/LoginPage.tsx
Labels: bug

#70 Feature/fix home errors
  src/components/collection/Pagination.tsx
  src/components/collection/ShareModal.tsx
  src/pages/collection/CollectionPage.tsx
Labels: bug

#73 merge: main <- develop
  src/components/collection/Pagination.tsx
  src/components/collection/ShareModal.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/Input.tsx
  src/components/layout/Footer.tsx
  src/pages/auth/SignupPage.tsx
  src/pages/collection/CollectionDetailPage.tsx
  src/pages/collection/CollectionPage.tsx
Labels: bug, enhancement

#74 merge: main <- develop
  src/pages/auth/LoginPage.tsx
  src/pages/auth/PasswordResetPage.tsx
  src/pages/auth/SignupPage.tsx
Labels: bug

#75 merge: main <- develop
  src/pages/auth/SignupPage.tsx
Labels: bug

#76 fix: 항목 선택 시 체크 처리, 버튼 노출 여부 수정
  src/components/collection/CollectionCard.tsx
  src/components/common/Alert.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/SearchBar.tsx
  src/components/reference/ReferenceCard.tsx
  src/components/reference/ReferenceList.tsx
  src/pages/collection/CollectionDetailPage.tsx
  src/pages/collection/CollectionPage.tsx
  src/pages/reference/ReferenceListPage.tsx
  src/store/collection.ts
  src/types/collection.ts
Labels: bug

#77 merge: main <- develop
  src/components/collection/CollectionCard.tsx
  src/components/common/Alert.tsx
  src/components/common/FloatingButton.tsx
  src/components/common/SearchBar.tsx
  src/components/reference/ReferenceCard.tsx
  src/components/reference/ReferenceList.tsx
  src/pages/collection/CollectionDetailPage.tsx
  src/pages/collection/CollectionPage.tsx
  src/pages/reference/ReferenceListPage.tsx
  src/store/collection.ts
  src/types/collection.ts
Labels: bug

#81 feat: 회원탈퇴 기능 개선
  dev-dist/sw.js
  src/components/common/Alert.tsx
  src/components/layout/Footer.tsx
  src/pages/auth/LoginPage.tsx
  src/services/auth.ts
  src/store/collection.ts
Labels: enhancement

#82 merge: main <- develop
  dev-dist/sw.js
  src/components/common/Alert.tsx
  src/components/layout/Footer.tsx
  src/pages/auth/LoginPage.tsx
  src/services/auth.ts
  src/store/collection.ts
Labels: enhancement

#88 fix: 사용자 공유 기능 오류 및 모드 해제 기능 추가
  src/components/collection/CollectionCard.tsx
  src/components/collection/ShareModal.tsx
  src/components/common/FloatingButton.tsx
  src/components/reference/ReferenceCard.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/collection/CollectionDetailPage.tsx
  src/pages/collection/CollectionPage.tsx
  src/pages/reference/ReferenceListPage.tsx
  src/router.tsx
  src/store/collection.ts
Labels: bug

#89 fix: 컬렉션 카드 더보기 버튼 노출 여부 수정
  src/components/collection/CollectionCard.tsx
Labels: bug

#91 fix: 오류 테스트 오류 사항 수정
  src/components/collection/CollectionCard.tsx
  src/components/layout/MainHeader.tsx
  src/components/reference/ReferenceList.tsx
  src/pages/reference/ReferenceListPage.tsx
Labels: bug
